//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 06:51:57 PM CST 
//

package com.ibm.commerce.qcheck.tools.config;

/*
 *-----------------------------------------------------------------
 * Copyright 2018 Trent Hoeppner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-----------------------------------------------------------------
 */

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The configuration of a scope with a particular name. The scope can be used to
 * configure groups of files according to certain criteria of those files. For
 * example, the "file" scope lets the user configure validators for filenames
 * that match a particular regular expression.
 * 
 * There can be many configurations with the same scope, although they should
 * have different names. When determining the validators for a particular scope,
 * if more than one config matches, only the first matching config element is
 * used.
 * 
 * There is one exception to the above - there should be at most one "global"
 * scope, and the name for this should be ".*" (no quotes). If more than one
 * "global" scope is specified, only the first will be used.
 * 
 * <p>
 * Java class for config complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="event" type="{http://www.validator.commerce.ibm.com/setup}event" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="scope" type="{http://www.validator.commerce.ibm.com/setup}scopeEnum" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Trent Hoeppner
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "config", namespace = "http://www.validator.commerce.ibm.com/setup", propOrder = { "event" })
public class Config {

	@XmlElement(required = true)
	protected List<Event> event;

	@XmlAttribute
	protected ScopeEnum scope;

	@XmlAttribute
	protected String name;

	/**
	 * Gets the value of the event property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the event property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEvent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Event }
	 * 
	 * 
	 */
	public List<Event> getEvent() {
		if (event == null) {
			event = new ArrayList<Event>();
		}
		return this.event;
	}

	/**
	 * Gets the value of the scope property.
	 * 
	 * @return possible object is {@link ScopeEnum }
	 * 
	 */
	public ScopeEnum getScope() {
		return scope;
	}

	/**
	 * Sets the value of the scope property.
	 * 
	 * @param value
	 *            allowed object is {@link ScopeEnum }
	 * 
	 */
	public void setScope(ScopeEnum value) {
		this.scope = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
