//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 06:51:57 PM CST 
//

package com.ibm.commerce.qcheck.tools.config;

/*
 *-----------------------------------------------------------------
 * Copyright 2018 Trent Hoeppner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-----------------------------------------------------------------
 */

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * The configuration of validators to be used for a particular time when
 * validation is performed. If this event occurs in a scope that has higher
 * precedence than a similar event in another scope, the levels for each
 * validator will be overriden by the levels in this scope.
 * 
 * <p>
 * Java class for event complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="validator" type="{http://www.validator.commerce.ibm.com/setup}validatorInst" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="time" type="{http://www.validator.commerce.ibm.com/setup}timeEnum" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Trent Hoeppner
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "event", namespace = "http://www.validator.commerce.ibm.com/setup", propOrder = { "validator" })
public class Event {

	@XmlElement(required = true)
	protected List<ValidatorInst> validator;

	@XmlAttribute
	protected TimeEnum time;

	/**
	 * Gets the value of the validator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the validator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getValidator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ValidatorInst }
	 * 
	 * 
	 */
	public List<ValidatorInst> getValidator() {
		if (validator == null) {
			validator = new ArrayList<ValidatorInst>();
		}
		return this.validator;
	}

	/**
	 * Gets the value of the time property.
	 * 
	 * @return possible object is {@link TimeEnum }
	 * 
	 */
	public TimeEnum getTime() {
		return time;
	}

	/**
	 * Sets the value of the time property.
	 * 
	 * @param value
	 *            allowed object is {@link TimeEnum }
	 * 
	 */
	public void setTime(TimeEnum value) {
		this.time = value;
	}

}
