//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 06:51:57 PM CST 
//

package com.ibm.commerce.qcheck.tools.config;

/*
 *-----------------------------------------------------------------
 * Copyright 2018 Trent Hoeppner
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-----------------------------------------------------------------
 */

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for timeEnum.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="timeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fulltoolkitbuild"/>
 *     &lt;enumeration value="incrementaltoolkitbuild"/>
 *     &lt;enumeration value="manual"/>
 *     &lt;enumeration value="asyoutype"/>
 *     &lt;enumeration value="wizard"/>
 *     &lt;enumeration value="integrationserverbuild"/>
 *     &lt;enumeration value="codereview"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 * @author Trent Hoeppner
 */
@XmlType(name = "timeEnum", namespace = "http://www.validator.commerce.ibm.com/setup")
@XmlEnum
public enum TimeEnum {

	@XmlEnumValue("fulltoolkitbuild")
	FULLTOOLKITBUILD("fulltoolkitbuild"), @XmlEnumValue("incrementaltoolkitbuild")
	INCREMENTALTOOLKITBUILD("incrementaltoolkitbuild"), @XmlEnumValue("manual")
	MANUAL("manual"), @XmlEnumValue("asyoutype")
	ASYOUTYPE("asyoutype"), @XmlEnumValue("wizard")
	WIZARD("wizard"), @XmlEnumValue("integrationserverbuild")
	INTEGRATIONSERVERBUILD("integrationserverbuild"), @XmlEnumValue("codereview")
	CODEREVIEW("codereview");

	private final String value;

	TimeEnum(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static TimeEnum fromValue(String v) {
		for (TimeEnum c : TimeEnum.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
